AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda for ephemeral-journal project. Handles read and write operations.
Resources:
  EphemeralJournalApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: Ephemeral Journal API Gateway
      StageName: Staging
      Cors: '*'
      Auth:
        DefaultAuthorizer: AWS_IAM

  EphemeralJournalLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'ephemeral-journal-lambda'
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: Lambda for ephemeral-journal project. Handles read and write operations.
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::458900578489:role/ephemeral-journal-lambda-role'
      Events:
        ReadFilePost:
          Type: Api
          Properties:
            Path: '/Entry/Read'
            Method: post
            RestApiId:
              Ref: EphemeralJournalApi
    DependsOn:
      - EphemeralJournalBkt

  EphemeralJournalBkt:
    Type: 'AWS::S3::Bucket'
    Properties: 
      BucketName: 'ephemeral-journal-bkt'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
